airbrake_api_key: 'use_local_settings'
default_display_timezone: 'Eastern Time (US & Canada)'
session_token: '123456789012345678901234567890'
github_key: 'use_local_settings'
github_secret: 'use_local_settings'
urlwriter_host: 'albatross.dev'
cron_notification_email: 'systemnotices@extension.org'
data_dump_mysql_cmd: 'use_local_settings'
data_dump_mysql_user: 'use_local_settings'
data_dump_mysql_pass: 'use_local_settings'
data_dump_gzip_cmd: 'use_local_settings'
data_dump_mysql_dump_cmd: 'use_local_settings'
data_dump_mysql_socket: 'use_local_settings'
data_dump_dir_dump: 'use_local_settings'
data_dump_mysql_host_development: 'use_local_settings'
data_dump_mysql_host_production_replica: 'use_local_settings'
sidekiq_enabled: true
slack_team: 'use_local_settings'
slack_token: 'use_local_settings'
slack_channel: 'use_local_settings'
