default_display_timezone: 'Eastern Time (US & Canada)'
session_token: '123456789012345678901234567890'
# testing place holder - use local settings
backup_key: 'supercalifragilisticexpialidocious'
github_key: 'use_local_settings'
github_secret: 'use_local_settings'
urlwriter_host: 'albatross.dev'
cron_notification_email: 'systemnotices@extension.org'
data_dump_mysql_cmd: 'use_local_settings'
data_dump_mysql_user: 'use_local_settings'
data_dump_mysql_pass: 'use_local_settings'
data_dump_gzip_cmd: 'use_local_settings'
data_dump_mysql_dump_cmd: 'use_local_settings'
data_dump_mysql_socket: 'use_local_settings'
data_dump_dir_dump: 'use_local_settings'
data_dump_mysql_host_aws_dev: 'use_local_settings'
data_dump_mysql_host_aws_prod: 'use_local_settings'
data_dump_mysql_host_scrubbed: 'use_local_settings'
data_dump_localdev_port: 8888
data_dump_php_cmd: 'use_local_settings'
honeybadger_api_key: 'use_local_settings'
sidekiq_enabled: true
slack_webhook: 'use_local_settings'
default_slack_channel: '#code_and_data'
deploys_slack_channel: '#code_and_data'
systems_slack_channel: '#systems'
slack_engbot_token: 'use_local_settings'
app_location: 'localdev'
