session_token: '123456789012345678901234567890'
github_key: 'use_local_settings'
github_secret: 'use_local_settings'
urlwriter_host: 'albatross.dev'
campfire_domain: 'use_local_settings'
campfire_token: 'use_local_settings'
campfire_room: 'use_local_settings'
campfire_verbose_room: 'use_local_settings'
